# Generated by Django 5.1.4 on 2025-01-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_proved',
            new_name='is_approved',
        ),
    ]
